print("Data do seu nascimento")
dia = int(input('Informe o dia: '))
mes = str(input('Informe o mês: '))
ano = int(input('Informe o ano: '))
print('Você nasceu no dia', dia,'de ' + mes + ' de', ano)